// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnZw57FDvUlUUo1andi7Ba_D0ETzMm0bk',
    appId: '1:738323576791:web:e9249c170de14ec338fd92',
    messagingSenderId: '738323576791',
    projectId: 'flutter-firebase-b243f',
    authDomain: 'flutter-firebase-b243f.firebaseapp.com',
    storageBucket: 'flutter-firebase-b243f.firebasestorage.app',
    measurementId: 'G-BFRBJX5VS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhbVaMNAILmWsEFRh-fdp1dmwFLAXWH68',
    appId: '1:738323576791:android:0a84ab5cc854fe5138fd92',
    messagingSenderId: '738323576791',
    projectId: 'flutter-firebase-b243f',
    storageBucket: 'flutter-firebase-b243f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXpVzL3XQxv15y-vMtVzOTyjC455CFrr8',
    appId: '1:738323576791:ios:e16a380ff4bbf96938fd92',
    messagingSenderId: '738323576791',
    projectId: 'flutter-firebase-b243f',
    storageBucket: 'flutter-firebase-b243f.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXpVzL3XQxv15y-vMtVzOTyjC455CFrr8',
    appId: '1:738323576791:ios:e16a380ff4bbf96938fd92',
    messagingSenderId: '738323576791',
    projectId: 'flutter-firebase-b243f',
    storageBucket: 'flutter-firebase-b243f.firebasestorage.app',
    iosBundleId: 'com.example.flutterTodoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnZw57FDvUlUUo1andi7Ba_D0ETzMm0bk',
    appId: '1:738323576791:web:f3ceb655685a433438fd92',
    messagingSenderId: '738323576791',
    projectId: 'flutter-firebase-b243f',
    authDomain: 'flutter-firebase-b243f.firebaseapp.com',
    storageBucket: 'flutter-firebase-b243f.firebasestorage.app',
    measurementId: 'G-1H9QSJDT9B',
  );
}
